version: '3'
services:
  mall-admin:
    image: mall/mall-admin:1.0.0-RELEASE
    container_name: mall-admin
    ports:
      - "8080:8080"
    volumes:
      - E:\docker/app/mall-admin/logs:/var/logs
    environment:
      - 'TZ="Asia/Shanghai"'
    external_links:
      - mysql:db #可以用db这个域名访问mysql服务
  mall-search:
    image: mall/mall-search:1.0.0-RELEASE
    container_name: mall-search
    ports:
      - "8081:8081"
    volumes:
      - E:\docker/app/mall-search/logs:/var/logs
    environment:
      - 'TZ="Asia/Shanghai"'
    external_links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
      - mysql:db #可以用db这个域名访问mysql服务
  mall-portal:
    image: mall/mall-portal:1.0.0-RELEASE
    container_name: mall-portal
    ports:
      - "8085:8085"
    volumes:
      - E:\docker/app/mall-portal/logs:/var/logs
    environment:
      - 'TZ="Asia/Shanghai"'
    external_links:
      - redis:redis #可以用redis这个域名访问redis服务
      - mongo:mongo #可以用mongo这个域名访问mongo服务
      - mysql:db #可以用db这个域名访问mysql服务
      - rabbitmq:rabbit #可以用rabbit这个域名访问rabbitmq服务